baseURL = 'https://ASVideo.github.io/'
languageCode = 'zh-tw'
defaultContentLanguage = "zh-tw"
theme = "hugo-theme-relearn"
title = 'Academia Sinica Video Archive'

metaDataFormat = "yaml"
# required for official documentation served from subfolder
relativeURLs = false
defaultContentLanguageInSubdir= false

[Params]
  editURL = "https://github.com/ASVideo/ASVideo.github.io/tree/main/content/"
  description = "AIGC-based Video Archive @ Academia Sinica"
  author = "Ling-Jyh Chen"
  alwaysopen = true
  showVisitedLinks = false
  disableSearch = false
  disableSearchHiddenPages = false
  #collapsibleMenu = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableLandingPageButton = true
  disableLanguageSwitchingButton = false
  disableSeoHiddenPages = false
  disableMermaid = false
  additionalContentLanguage = [ "zh-tw"]
  #customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  titleSeparator = "::"

[taxonomies]
  category = "categories"
  tag = "tags"
  level = "levels"
  author = "authors"

[outputs]
  home = ["HTML", "RSS", "SEARCH", "SEARCHPAGE"]
  section = ["HTML", "RSS", "PRINT"]
  page = ["HTML", "RSS", "PRINT"]

[module]
  [[module.mounts]]
    source = 'archetypes'
    target = 'archetypes'
  [[module.mounts]]
    source = 'assets'
    target = 'assets'

  # Language dependend settings:
  # Use case https://gohugo.io/content-management/multilingual/#translation-by-filename
  [[module.mounts]]
    source = 'content'
    target = 'content'
  # Use case https://gohugo.io/content-management/multilingual/#translation-by-content-directory
  #[[module.mounts]]
  #  lang = 'en'
  #  source = 'content/en'
  #  target = 'content'
  #[[module.mounts]]
  #  lang = 'pir'
  #  source = 'content/pir'
  #  target = 'content'

  [[module.mounts]]
    source = 'data'
    target = 'data'
  [[module.mounts]]
    source = 'i18n'
    target = 'i18n'
  [[module.mounts]]
    source = '../images'
    target = 'static/images'
  [[module.mounts]]
    source = 'layouts'
    target = 'layouts'
  [[module.mounts]]
    source = 'static'
    target = 'static'


[Languages]
[Languages.zh-tw]
title = "科普影音資料庫"
weight = 1
languageName = "中文"
landingPageURL = "/"
landingPageName = "<i class='fas fa-home'></i> 首頁"

[[Languages.zh-tw.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub"
identifier = "ds"
url = "https://github.com/ASVideo/ASVideo.github.io"
weight = 10


[Languages.en]
title = "Academia Sinica Popular Science Video Archive"
weight = 2
languageName = "English"
landingPageURL = "/"
landingPageName = "<i class='fas fa-home'></i> Home"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub"
identifier = "ds"
url = "https://github.com/ASVideo/ASVideo.github.io"
weight = 10

[Languages.ja]
title = "中央研究院の人気科学視聴覚データベース"
weight = 3
languageName = "日本語"
landingPageURL = "/"
landingPageName = "<i class='fas fa-home'></i> Home"

[[Languages.ja.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub"
identifier = "ds"
url = "https://github.com/ASVideo/ASVideo.github.io"
weight = 10

